Trust/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('trust-management/', admin.site.urls),
    path('', include('core.urls',namespace='core')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)                          

core/urls.py
from django.urls import path
from . import views
from django.conf.urls import (handler400, handler403, handler404)
# from allauth.account.views import SignupView
from .views import (  
    Home,
    Blog_page,
    Obanna,
    Events_page,
    About,
    Gallery_page,
    Blogs,
    Videos,
)

app_name = 'core'
 
urlpatterns = [
    path('', Home.as_view(), name='home'),      
    path('blog/<int:pk>/', Blog_page.as_view(), name='blog-detail'),      
    path('gallery/', Gallery_page.as_view(), name='gallery'),
    path('blogs/', Blogs.as_view(), name='blogs'),      
    path('events/', Events_page.as_view(), name='events'),
    path('obanna/', Obanna, name='obanna'), 
    path('youtubevideos/', Videos, name='videos'),     
    path('about/', About, name='about'), 
]

core/models.py
from django.db.models.signals import post_save,pre_save
from django.conf import settings
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.db.models import Sum
from django.shortcuts import reverse
from django.utils import timezone

STATUS = (
    ('O','Ongoing'),
    ('C','Completed'),
    ('U','Upcomming')
)


class Carousal(models.Model):
    image = models.ImageField(upload_to='casrousal/', null=True)
    link = models.URLField(max_length = 200)
    update_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Slide-{self.pk}"

class Gallery(models.Model):
    image = models.ImageField(upload_to='gallery/', null=True)    
    update_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Image-{self.pk}"

class Event(models.Model):    
    title = models.CharField(max_length=50)
    description = models.TextField()
    venue = models.CharField(max_length=100)
    image = models.ImageField(upload_to='events/', null=True)
    time = models.DateTimeField()
    status = models.CharField(default='O',choices=STATUS,max_length = 5)
    update_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title}"

class Blog(models.Model):    
    title = models.CharField(max_length=35)
    image1 = models.ImageField(upload_to='blogs/', null=True)    
    first_paragraph = models.TextField()
    image2 = models.ImageField(upload_to='blogs/', null=True)
    second_paragraph = models.TextField()
    author_name = models.CharField(max_length=100)    
    read_time = models.IntegerField()        
    homepage_display = models.BooleanField(default=False)
    update_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title}"        

class TrustMember(models.Model):
    name = models.CharField(max_length=20)
    email = models.CharField(max_length=20) 
    phone = models.CharField(max_length=20)
    address = models.TextField()

    def __str__(self):
        return f"{self.name}"
        
class TrustTeamMember(models.Model):
    name = models.CharField(max_length=20)
    designation = models.CharField(max_length=100)
    image = models.ImageField(upload_to='members/', null=True)
    email = models.CharField(max_length=20) 
    phone = models.CharField(max_length=20)
    address = models.TextField()

    def __str__(self):
        return f"{self.name}"        
        
class YouTubeVideo(models.Model):
    video_id = models.CharField(max_length=20)  
    update_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Video-{self.pk}"        

core/views.py
from django.conf import settings
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, View
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.utils import timezone
import random
from django.shortcuts import reverse
import string
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login as auth_login
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import smtplib
from django.core.paginator import Paginator
from email.message import EmailMessage
from datetime import datetime, timedelta
from django.db.models import Q
from .models import Gallery, Blog, Event, Carousal, TrustMember, TrustTeamMember, YouTubeVideo
from django.db.models.functions import ( ExtractDay, ExtractHour, ExtractMinute, ExtractMonth, ExtractSecond, ExtractWeek, ExtractWeekDay, ExtractYear )
from django.utils.html import format_html

class Home(View):
    template_name='home.html'
    def get(self, *args, **kwargs):
        carousal = Carousal.objects.all()
        gallery = Gallery.objects.all()
        u = Event.objects.filter(status="U").order_by('-id')
        e = Event.objects.filter(status="O").order_by('-id')
        events = u | e 
        blogs = Blog.objects.filter(homepage_display=True)
        context={ 'carousal':carousal,'gallery':gallery, 'events':events, 'blogs':blogs }        
        return render(self.request,self.template_name,context=context)
    def post(self, *args, **kwargs):
        name = self.request.POST.get('name')
        email =  self.request.POST.get('email')
        phone =  self.request.POST.get('phone')
        address =  self.request.POST.get('address')
        TrustMember.objects.create(name=name,email=email,phone=phone,address=address)
        return redirect('core:home')

class Blog_page(View):
    template_name='blog.html'
    def get(self, *args, **kwargs):
        blog = Blog.objects.get(pk=kwargs['pk'])
        blogs = Blog.objects.all().exclude(pk=kwargs['pk']).order_by('-id')
        context={ 'blog':blog,'blogs':blogs}        
        return render(self.request,self.template_name,context=context)

class Blogs(View):
    template_name='allblogs.html'
    def get(self, *args, **kwargs):        
        blogs = Blog.objects.all().order_by('-id')
        context={'blogs':blogs}        
        return render(self.request,self.template_name,context=context)

class Gallery_page(View):
    template_name='gallery.html'
    def get(self, *args, **kwargs):
        vids = YouTubeVideo.objects.all()
        count = Gallery.objects.all().count()
        images1 = Gallery.objects.all().order_by('-id')[0:int(count/4)]
        images2 = Gallery.objects.all().order_by('-id')[int(count/4):int(count/2)]
        images3 = Gallery.objects.all().order_by('-id')[int(count/2):int(3*count/4)]
        images4 = Gallery.objects.all().order_by('-id')[int(3*count/4):int(count)]
        context={ 'images1':images1,'images2':images2,'images3':images3,'images4':images4,'vids':vids}        
        return render(self.request,self.template_name,context=context)

class Events_page(View):
    template_name='events.html'
    def get(self, *args, **kwargs):
        uevents = Event.objects.filter(status="U")
        oevents = Event.objects.filter(status="O")
        cevents = Event.objects.filter(status="c")
        context={ 'uevents':uevents,'cevents':cevents,'oevents':oevents}        
        return render(self.request,self.template_name,context=context)

def Obanna(request):
    return render(request,'obanna.html')
    
def Videos(request): 
    vids = YouTubeVideo.objects.all()
    context={ 'vids':vids}  
    return render(request,'youtubevideos.html',context=context)    

def About(request):
    members = TrustTeamMember.objects.all()
    context={'members':members}
    return render(request,'about.html',context=context)

templates/404error.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=0.3, shrink-to-fit=yes">
  <meta http-equiv="x-ua-compatible" content="ie=edge"> 
  <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/gif" sizes="16x16">
  <title>4o4</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <style>
  body{
  background-image: url("https://cdn.dribbble.com/users/285475/screenshots/2083086/dribbble_1.gif");
  background-color: #fff;
  color:#000;
  height: 100%;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  }
  @media only screen and (max-width: 1000px) {
  body {
    height: 100%;
    width: 320px;
  }
  h5,a{
  font-size: 3em;
  }
}
  </style>
</head>
<body>
    <center class="mt-5 pt-3">
    <h5 >Opps! Page not found</h5>
    <a class="btn rounded mt-2" style="background-color:#fff;color:#000;font-size: 3em" href="/">Go back to Homepage</a>
    </center>
    </div>
</body>
</html>

templates/413error.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>413</title>

<link href="https://fonts.googleapis.com/css?family=Montserrat:500" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Titillium+Web:700,900" rel="stylesheet">



<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>
<body>
<div id="notfound">
<div class="notfound">

<h1>Oops! This Page Could Not Be Found</h1>
<h2>Sorry, you are getting this error because your file(image) is too large.....</h2>
<p>Sorry but the page you are looking for does not exist, have been removed. name changed or is temporarily unavailable</p>
<a href="https://www.presimax.online/">Go To Homepage</a>
</div>
</div>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="de4b7f015ede2edfc39f0b2d-text/javascript"></script>
<script type="de4b7f015ede2edfc39f0b2d-text/javascript">
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="de4b7f015ede2edfc39f0b2d-|49" defer=""></script></body>
</html>

templates/500error.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>500</title>

<link href="https://fonts.googleapis.com/css?family=Montserrat:500" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Titillium+Web:700,900" rel="stylesheet">



<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>
<body>
<div id="notfound">
<div class="notfound">
<h2>Oops! This Page Could Not Be Found</h2>
<p>Sorry but the page you are looking for does not exist, have been removed. name changed or is temporarily unavailable</p>
<a href="https://www.presimax.online/">Go To Homepage</a>
</div>
</div>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="de4b7f015ede2edfc39f0b2d-text/javascript"></script>
<script type="de4b7f015ede2edfc39f0b2d-text/javascript">
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="de4b7f015ede2edfc39f0b2d-|49" defer=""></script></body>
</html>

templates/blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{blog.title}}</title>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <meta name="google-site-verification" content="rjE54tymdHYjM1qWAnDIjrrq5iOoml4HTG2tLXe4C0M" />
    <meta name="description" content="VOICE Trust is a non-profitable organization which serves poor and needy people. Join us, with your Humanity, together let's serve people.">
    <meta name="keywords" content="VOICE Trust,voicetrust.org, voicetrust.org.in, Vadde Obanna, Vaddera, Vadde, Obanna, Voicetrust, voicetrust, VoiceTrust, charity, Trust, Trust in Ap, Trust in Andhra, Voice Trust AP">
    <meta name=”robots” content="index, follow">
    <!--  for social media -->
    <meta property="og:title" content="VOICE Trust" />
    <meta property="og:description" content="VOICE Trust is a non-profitable organization which serves poor and needy people. Join us, with your Humanity, together let's serve people." />
    <meta property="og:image" content="https://voicetrust.org.in/media/favicons/apple-touch-icon.png" />
    <!--  for social media -->
    <link rel="apple-touch-icon" sizes="180x180" href="https://voicetrust.org.in/media/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="https://voicetrust.org.in/media/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="https://voicetrust.org.in/media/favicons/favicon-16x16.png">
    <link rel="manifest" href="https://voicetrust.org.in/media/favicons/site.webmanifest">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">       
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">        
        <span class="head"><h2>{{ blog.title }}</h2> <a class="fal fa-share-alt" href="whatsapp://send?text={{ request.get_full_path }}"></a></span>
        <div class="contentbx">
            <div class="imgbx">
                <img src="{{blog.image1.url}}" alt="">
            </div>
            <p class="text first">
               {{blog.first_paragraph}}
            </p>
            <div class="imgbx">
                <img src="{{blog.image1.url}}" alt="">
            </div>
            <p class="text">
                {{blog.second_paragraph}}
            </p>
        </div>
    </div>
    <!-- <div class="see flex">
        <div class="view">
            <span class="fal fa-eye mr-1"></span><span>0</span>
        </div>                    
        <div class="social">
            <span class="fal fa-thumbs-up mr-1"></span>                
            <span class="far fa-share-alt"></span>    
        </div>
    </div> -->
    <div class="hor-line"></div>
    <section data-aos="fade-up-right" class="blogs" id="blogs">
        <div class="heading">
            <h1>View more <span>A</span>rticles</h1>
        </div>
        <div class="container">
            {% for i in blogs %}
            <div onclick="location.href={% url 'core:blog-detail' i.id %}" data-aos="zoom-in-up" class="card">
                <div onclick="location.href='{% url 'core:blog-detail' i.id %}'" class="imgbx">
                    <img src="{{i.image1.url}}" alt="image">
                </div>
                <div onclick="location.href='{% url 'core:blog-detail' i.id %}'" class="contentbx">
                    <h3 onclick="location.href='{% url 'core:blog-detail' i.id %}'">{{ i.title }}</h3>
                    <p onclick="location.href={% url 'core:blogs' %}" class="more">{{ i.first_paragraph }}</p>                    
                </div>
                </div>
            {% endfor %}                    
        </div>
    </section>
    <section class="footer">
        <div class="social-icons">
            <a href="https://www.facebook.com/VOICE-TRUST-100146648771490/" class="fab fa-facebook-f"></a>
            <a href="https://youtube.com/playlist?list=PLoZAdQtLdBfDT6ukeCrTzNtAEDcHdUS6U" class="fab fa-youtube"></a>
            <a href="https://twitter.com/BalaNarasimhud3?s=08" class="fab fa-twitter"></a>
        </div>
        <div class="copyright-act">
            <span>&#169; All rights reserverd by VOICE Trust. Powered by Presimax sof sols.</span>
        </div>
    </section>
</body>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script>
    $(document).ready(function(){
     $(window).scroll(function(){
         if (($(window).scrollTop() > 0 )){
             $('.navbar').addClass( "sticky");
         }
         else{
             $('.navbar').removeClass( "sticky");
         }
 
     });
 });
 </script>
 <script>
     const togglemenu = () => {
         $('.close').toggle();
         $('.menu-bar').toggle();
         $('.menu-overlay').toggleClass('flex');
     }
 </script>
 <script type="text/javascript">
 function googleTranslateElementInit() {
     new google.translate.TranslateElement({pageLanguage: 'en', includedLanguages : 'te,en'}, 'google_translate_element');
 }
 </script>
</html>

templates/gallery.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gallery | Voice Trust</title>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <meta name="description" content="VOICE Trust is a non-profitable organization which serves poor and needy people. Join us, with your Humanity, together let's serve people.">
    <meta name="keywords" content="VOICE Trust,voicetrust.org, voicetrust.org.in, Vadde Obanna, Vaddera, Vadde, Obanna, Voicetrust, voicetrust, VoiceTrust, charity, Trust, Trust in Ap, Trust in Andhra, Voice Trust AP">
    <meta name=”robots” content="index, follow">
    <!--  for social media -->
    <meta property="og:title" content="VOICE Trust" />
    <meta property="og:description" content="VOICE Trust is a non-profitable organization which serves poor and needy people. Join us, with your Humanity, together let's serve people." />
    <meta property="og:image" content="https://voicetrust.org.in/media/favicons/apple-touch-icon.png" />
    <!--  for social media -->
    <link rel="apple-touch-icon" sizes="180x180" href="https://voicetrust.org.in/media/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="https://voicetrust.org.in/media/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="https://voicetrust.org.in/media/favicons/favicon-16x16.png">
    <link rel="manifest" href="https://voicetrust.org.in/media/favicons/site.webmanifest">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <style>
        .heading{
            margin-top: 7rem;
            margin-bottom: 3rem;
        }
        .bxcontent{
            padding: 1rem;
            display: flex;
            flex-wrap: wrap;
        }
        @media screen and (max-width:600px){
            .bxcontent{
            padding: 0.5rem;
        }   
        }


        .row {
        display: flex;
        flex-wrap: wrap;
        padding: 0 1rem;
        margin: 1rem auto;
        }
        
        .row1 {
        display: flex;
        flex-wrap: wrap;
        padding: 0 1rem;
        margin: 1rem auto;
        justify-content:space-evenly;
        align-items:center;
        }
        .row1 > iframe{
          margin:1rem auto;
        }

        .column {
        flex: 25%;
        max-width: 25%;
        padding: 0 0.5rem;
        }

        .column img {
        margin-top: 8px;
        vertical-align: middle;
        width: 100%;
        }


        @media screen and (max-width: 800px) {
        .column {
            flex: 50%;
            max-width: 50%;
        }
        }

        @media screen and (max-width: 600px) {
        .column {
            flex: 100%;
            max-width: 100%;
        }
        }
        .heading{
            justify-content: center !important;
        }
    </style>
</head>
<body>
{% include 'navbar.html' %}
    <div class="bxcontainer">                
        <div class="heading">
            <h1><span>G</span>allery</h1>
        </div>    
        <div class="bxcontent" onclick="location.href={% url 'core:videos' %}" style="cursor:pointer" >
            <div class="row1" onclick="location.href={% url 'core:videos' %}" style="cursor:pointer" >
            {% for v in vids %}
              <iframe onclick="location.href={% url 'core:videos' %}"  width="460" height="315" src="https://youtube.com/embed/{{ v.video_id }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>   
             {% endfor %}          
            </div>
        </div>
        <div class="bxcontent">
            <div class="row">
                <div class="column">
                    {% for image in images1 %}
                    <div class="bximg">
                        <img src="{{image.image.url}}" alt="">
                    </div>                   
                    {% endfor %}
                </div>
                    <div class="column">
                        {% for image in images2 %}
                        <div class="bximg">
                            <img src="{{image.image.url}}" alt="">
                        </div>                   
                        {% endfor %}
                    </div>
                    <div class="column">
                        {% for image in images3 %}
                        <div class="bximg">
                            <img src="{{image.image.url}}" alt="">
                        </div>                   
                        {% endfor %}
                    </div>
                    <div class="column">
                        {% for image in images4 %}
                        <div class="bximg">
                            <img src="{{image.image.url}}" alt="">
                        </div>                   
                        {% endfor %}    
                    </div>
                </div>                
            </div>
        </div>
    </div>
    <section class="footer">
        <div class="social-icons">
            <a href="#" class="fab fa-facebook-f"></a>
            <a href="#" class="fab fa-instagram"></a>
            <a href="#" class="fab fa-twitter"></a>
        </div>
        <div class="copyright-act">
            <span>&#169; All rights reserverd by VOICE Trust. Powered by Presimax sof sols.</span>
        </div>
    </section>
</body>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script>
    $(document).ready(function(){
     $(window).scroll(function(){
         if (($(window).scrollTop() > 0 )){
             $('.navbar').addClass( "sticky");
         }
         else{
             $('.navbar').removeClass( "sticky");
         }
 
     });
 });
 </script>
 <script>
     const togglemenu = () => {
         $('.close').toggle();
         $('.menu-bar').toggle();
         $('.menu-overlay').toggleClass('flex');
     }
 </script>
 <script type="text/javascript">
 function googleTranslateElementInit() {
     new google.translate.TranslateElement({pageLanguage: 'en', includedLanguages : 'te,en'}, 'google_translate_element');
 }
 </script> 
</html>    

templates/navbar.html
{% load static %}
<div class="menu-overlay">
    <ul class="items">
        <li onclick="togglemenu()"><a href="/">Home</a></li>
        <li onclick="togglemenu()"><a href="/about">About Us</a></li>        
        <li onclick="togglemenu()"><a href="/gallery">Gallery</a></li>
        <li onclick="togglemenu()"><a href="/events">Events</a></li>
        <li onclick="togglemenu()"><a href="/blogs">Blogs</a></li>
        <li onclick="togglemenu()"><a href="/obanna">Vadde Obanna</a></li>
        <li onclick="togglemenu()"><a href="#contact">Contact Us</a></li>
        <li><a id="google_translate_element"></a></li>
    </ul>
</div>    
<header>        
    <div class="navbar">
        <div class="logo" onclick="javascript:location.href='/'" >
            <span>V</span>OICE <span>T</span>rust
        </div>        
        <div onclick="javascript:location.href='/'" style="cursor: pointer;" class="logo-img">
            <img onclick="javascript:location.href='/'" src="{% static 'images/vol.png' %}" alt="">
        </div>    
        <div class="small-screen bared">
            <div class="icons">
                <div class="icon menu-bar" onclick="togglemenu()">
                    <span class="far fa-bars"></span>
                </div>                    
                <div class="icon close" onclick="togglemenu()">
                    <span class="far fa-times"></span>
                </div>
            </div>                
        </div>
        <div class="menu">                
            <ul class="items">
                <li><a href="/">Home</a></li>
                <li><a href="/about">About Us</a></li>                    
                <li><a href="/events">Events</a></li>
                <li><a href="/gallery">Gallery</a></li>  
                <li><a href="/blogs">Blogs</a></li>
                <li><a href="/obanna">Vadde Obanna</a></li>
                <li><a href="#contact">Contact Us</a></li>
                <li><div id="google_translate_element1"></div></li>
            </ul>
        </div>
    </div>
</header>

templates/temp.html
<div class="images">
  {% for i in gallery %}
  <div class="img" style="--p:{{forloop.counter}}">
      <img src="{{ i.image.url }}" alt="image">
  </div>    
  {% endfor %}        
</div>